---
name: {{PROJECT}}-compliance-matrix
description: Draft the bidder's answers to the {{PROGRAM}} compliance / requirements matrix item by item (complies / partially / does not comply / to confirm, fulfillment mode, justification), citing the knowledge base for every statement and listing the gaps that need a decision. Use when the user asks to fill, review, pre-answer or check coverage of the compliance matrix, a workstream of it, or specific requirement ids. Writes drafts to docs/ only. For general questions about the request documents use /kb instead.
---

<!-- generated by kb-setup v{{ENGINE_VERSION}} from preset rfi-proposal on {{DATE}}; regeneration shows a diff first and keeps sections marked manual -->

# {{PROJECT}}-compliance-matrix

Drafts compliance answers for `{{COMPLIANCE_MATRIX_FILE}}`. The matrix rows are already in the KB as `{{PREFIX}}:ComplianceItem`, one entity per item id, with sheet and row.

## Rules

- **Facts come from the KB.** Run from the workspace root, one simple command per Bash call. Below, `KB` means `uv run ~/.claude/skills/kb-setup/scripts/kb.py`:
  - `KB ask "<question>"`: best entities with winning values and citations;
  - `KB query <saved-query> [--param k=v]`;
  - `KB show <id | label | IRI>`: everything about one entity, with sources and precedence;
  - `KB search "<text>" --cls {{PREFIX}}:ComplianceItem`.

  Never run curator commands (`update`, `lock`, `extract-*`); they belong to `/kb`.
- **Document text only in subagents.** When a KB excerpt is not enough (full page, long section, figure), delegate to a `general-purpose` subagent. Its prompt must be self-contained (paths, pages, what to return). It may use `KB page-text <md> <page>` and must return a compact answer with citations. Never read `raw/` files in the main context.
- **Never write to `raw/` or `wiki/`.** Do not edit the original spreadsheet. Output goes to `docs/compliance-matrix/`. A filled copy of the spreadsheet, if the user asks for one, is written in `docs/` too.
- **Cite everything:** `file, sheet X, row N` for matrix items and `file, p.N` for document passages. Say when support comes from a wiki note (team knowledge) rather than from the issuer's documents. Repeat any `ALERT`/`WARNING` line printed by the engine.
- **Never invent compliance.** The issuer's documents describe what is required, not what the bidder offers. Evidence of the bidder's capability comes from wiki notes (team decisions, solution notes) or from the user. Without evidence, the answer is **To confirm**, and the item goes to the gap list.
- Chat answers are in the user's language. The draft is in **{{PROPOSAL_LANGUAGE}}**, the language the proposal must be written in, unless the user says otherwise.

## Schema cheat sheet (do not read the .ttl)

- `{{PREFIX}}:ComplianceItem` has these properties:
  - `kb:originalId`: item id;
  - `kb:excerpt`: requirement text;
  - `{{PREFIX}}:category`, `{{PREFIX}}:workstream`, `{{PREFIX}}:grouping`, `{{PREFIX}}:macroRequirement`, `{{PREFIX}}:deploymentScope`;
  - `{{PREFIX}}:eligibility`: mandatory / important / desirable;
  - `{{PREFIX}}:compliance`, `{{PREFIX}}:fulfillmentMode`, `{{PREFIX}}:effort`, `{{PREFIX}}:bidderComment`, `{{PREFIX}}:clientComment`;
  - `kb:sheet`, `kb:row`, `kb:definedIn`.
- Extra classes: `{{PREFIX}}:FunctionalRequirement`, `NonFunctionalRequirement`, `SecurityRequirement`, `QualityRequirement`. There is no inference, so query concrete classes.
- Context:
  - `kb:Section` (label, `kb:number`, `kb:page`, `kb:excerpt`);
  - `kb:Fact` and `kb:Deadline` with `kb:topic`;
  - `{{PREFIX}}:ContractClause`;
  - wiki notes (`kb:WikiNote`).

## Workflow

1. **Scope.** Settle what is being answered: all items, one workstream, mandatory only, or a list of ids. Ask if unclear. List the scope with `KB query requirements-by-topic --param workstream="<regex>" --param section="<regex>"`. Use `"."` to match everything.
2. **Per item:**
   1. `KB show <id>`: requirement text, eligibility, existing answers and comments.
   2. `KB ask "<key terms of the requirement>"`: request-document sections that detail or constrain it, related facts, deadlines and wiki notes about the bidder's solution.
   3. If the sources disagree (the engine shows a conflict and a winner), use the winning value and mention the divergence.
3. **Batches.** For more than about 25 items, split by workstream into parallel subagents with the same rules and output format. Each subagent returns its table plus counts. Check that each one actually ran its commands, and re-run any that come back suspiciously fast.
4. **Draft the answer per item:**
   - proposed compliance (Complies / Partially complies / Does not comply / To confirm);
   - fulfillment mode (native, configuration, customization, third party, roadmap);
   - a 1–3 sentence justification;
   - sources;
   - open question, if any.
5. **Gaps.** Run `KB query gaps` and add:
   - items without evidence;
   - mandatory items answered "Partially" or "Does not comply";
   - items whose issuer comment asks for something not yet covered.
6. **Write** `docs/compliance-matrix/<YYYY-MM-DD>-<scope-slug>.md` with:
   - header: scope, date, KB status line, sources used;
   - answer table: id | requirement (short) | eligibility | proposed compliance | fulfillment mode | justification | sources;
   - gap list: id | why | who must decide;
   - counts per compliance value.

   Tell the user the path.
7. **Report in chat:** counts, the most critical gaps (mandatory first), conflicts found, and what needs a decision from the team.

## Improvement suggestions

End with this section only when signals appeared. Examples:
- a requirement kept returning nothing from `KB ask`, so the team should write a wiki note about the solution capability;
- a matrix column is missing from the mapping;
- a repeated ad-hoc query should become a saved query;
- a numeric value diverges between documents but no `facts` rule covers it.

Offer to log the suggestions in `kb/IMPROVEMENTS.md`.
