---
name: {{PROJECT}}-raci
description: Analyze the {{PROGRAM}} RACI / responsibility matrices — what each role (ours and the client's) is responsible, accountable, consulted or informed for, by phase — and find conflicts between matrices, activities without a responsible or accountable, and activities with more than one accountable, citing sheet and row. Use when the user asks who does what, what the bidder must staff or assume, or to compare or check the RACI matrices. Writes reports to docs/ only. For other questions about the documents use /kb.
---

<!-- generated by kb-setup {{KB_SETUP_VERSION}} from preset rfi-proposal on {{DATE}}; regeneration shows a diff first and keeps sections marked manual -->

# {{PROJECT}}-raci

RACI spreadsheets in the KB: {{RACI_FILES}}. Every non-empty cell is a `kb:RACIAssignment`. Roles with the same header text in different files are the same `kb:Role`. The bidder's roles are: {{BIDDER_ROLES}}.

## Rules

- **Facts come from the KB.** Run from the workspace root, one simple command per Bash call. Below, `KB` means `uv run ~/.claude/skills/kb-setup/scripts/kb.py` if that file exists, else `uv run scripts/kb-engine/kb.py` (workspace copy); if neither exists, follow the engine rules of the `/kb` skill (offer to install kb-setup):
  - `KB query <saved-query | SPARQL text>`;
  - `KB show <role | activity>`;
  - `KB ask "<question>"`.

  Never run curator commands; they belong to `/kb`.
- **Document text only in subagents.** If a RACI exists only as a figure in a document, or an activity needs its description from a document, delegate to a `general-purpose` subagent with a self-contained prompt. It may use `KB page-text <md> <page>` and returns compact results with citations. Image-based matrices are described in the KB; treat low-resolution transcriptions as uncertain and say so.
- **Never write to `raw/` or `wiki/`.** Reports go to `docs/raci/`.
- **Cite** `file, sheet X, row N` for every assignment. Repeat engine `ALERT`/`WARNING` lines. Answer in the user's language.

## Schema cheat sheet (do not read the .ttl)

- `kb:RACIAssignment` has `kb:activity`, `kb:role`, `kb:raciCode` ("R", "A", "R/A"...), `kb:sheet`, `kb:row` and `kb:definedIn`.
- `kb:Activity` has:
  - label;
  - `kb:phase`, `{{PREFIX}}:phasePMO`;
  - `kb:order`, `kb:description`;
  - `kb:deliverable` → `kb:Deliverable`, `{{PREFIX}}:deliverableType`;
  - `kb:responsible` / `kb:accountable` / `kb:consulted` / `kb:informed` → `kb:Role`.

## Workflow

1. **Responsibilities by role:** `KB query raci-by-role`. If the output is long (hundreds of rows), run it in a subagent that filters by the requested role or phase and returns a compact table.
2. **Checks.** Run each one as a separate command:
   - Gaps (no R or no A): `KB query gaps`, rows "activity without responsible (R)" and "activity without accountable (A)".
   - More than one accountable for an activity (RACI rule: exactly one A):
     ```
     KB query 'SELECT ?activity ?source (GROUP_CONCAT(DISTINCT ?rl; separator=", ") AS ?accountables) WHERE { ?a a kb:Activity ; rdfs:label ?activity ; kb:accountable ?r ; kb:definedIn ?d . ?r rdfs:label ?rl . ?d dcterms:source ?source } GROUP BY ?activity ?source HAVING (COUNT(DISTINCT ?r) > 1)'
     ```
   - The same role and the same activity name with different codes in two matrices:
     ```
     KB query 'SELECT DISTINCT ?role ?activity ?code1 ?src1 ?code2 ?src2 WHERE { ?x1 a kb:RACIAssignment ; kb:role ?r ; kb:activity ?a1 ; kb:raciCode ?code1 ; kb:definedIn ?d1 . ?x2 a kb:RACIAssignment ; kb:role ?r ; kb:activity ?a2 ; kb:raciCode ?code2 ; kb:definedIn ?d2 . ?a1 rdfs:label ?activity . ?a2 rdfs:label ?l2 . FILTER(STR(?d1) < STR(?d2) && LCASE(STR(?activity)) = LCASE(STR(?l2)) && ?code1 != ?code2) ?r rdfs:label ?role . ?d1 dcterms:source ?src1 . ?d2 dcterms:source ?src2 }'
     ```
   - Activities that are equivalent but named differently across matrices: give a subagent the `raci-by-role` output of both files and ask it to pair similar activities and compare their codes. It returns pairs with sheet and row, and a confidence level.
3. **Implications for the proposal:**
   - for the bidder's roles, list every R and A by phase: what the team must staff, deliver and approve;
   - list the client-side dependencies (activities where the client is R/A and the bidder depends on the output);
   - list the role names that do not map to the bidder's organization, as questions for the team.
4. **Write** `docs/raci/<YYYY-MM-DD>-<topic-slug>.md` with:
   - per-role tables: role | phase | activity | code | source;
   - conflicts and gaps, with citations;
   - implications;
   - open questions.

   Tell the user the path.
5. **Report in chat:** counts per role and code, conflicts, gaps, top questions.

## Improvement suggestions

End with this section only when signals appeared. Examples:
- the same role is spelled differently across files, so roles do not converge (suggest normalizing headers in the mapping or a wiki note mapping the names);
- the matrix uses letters other than R/A/C/I;
- a check here was run often enough to become a saved query;
- a RACI exists only as an image.

Offer to log the suggestions in `kb/IMPROVEMENTS.md`.
