---
name: {{PROJECT}}-transition-checklist
description: Go through the {{PROGRAM}} transition / knowledge-transfer checklist (project to operations) item by item and state what the proposal must cover for each — deliverable, phase, owner, related requirements, deadlines such as assisted operation, warranty and exit assistance — citing the knowledge base, and flag items not yet covered by the proposal drafts. Use when the user asks about transition, handover, knowledge transfer, go-live readiness or the transition checklist. Writes to docs/ only. For other questions about the documents use /kb.
---

<!-- generated by kb-setup {{KB_SETUP_VERSION}} from preset rfi-proposal on {{DATE}}; regeneration shows a diff first and keeps sections marked manual -->

# {{PROJECT}}-transition-checklist

The checklist `{{TRANSITION_CHECKLIST_FILE}}` is in the KB as `{{PREFIX}}:TransitionChecklistItem`, one entity per numbered item, with sheet and row.

## Rules

- **Facts come from the KB.** Run from the workspace root, one simple command per Bash call. Below, `KB` means `uv run ~/.claude/skills/kb-setup/scripts/kb.py` if that file exists, else `uv run scripts/kb-engine/kb.py` (workspace copy); if neither exists, follow the engine rules of the `/kb` skill (offer to install kb-setup):
  - `KB query <saved-query | SPARQL text>`;
  - `KB show <id | label>`;
  - `KB ask "<question>"`.

  Never run curator commands; they belong to `/kb`.
- **Document text only in subagents.** Full passages of the request documents, and the coverage check against the drafts in `docs/proposal/`, run in `general-purpose` subagents. Each gets a self-contained prompt and returns a compact table with citations. Never read `raw/` files in the main context.
- **Never write to `raw/` or `wiki/`.** Output goes to `docs/transition/`.
- **Cite** `file, sheet X, row N` for checklist items and `file, p.N` for document passages. Repeat engine `ALERT`/`WARNING` lines. Answer in the user's language. Write the deliverable in {{PROPOSAL_LANGUAGE}} unless told otherwise.

## Schema cheat sheet (do not read the .ttl)

- `{{PREFIX}}:TransitionChecklistItem` has:
  - `kb:originalId` (item number) and `kb:excerpt` (item text);
  - `{{PREFIX}}:applicable`, `{{PREFIX}}:status`;
  - `kb:phase` (when it is produced);
  - `{{PREFIX}}:storageLocation`, `{{PREFIX}}:nonConformityType`;
  - `kb:sheet`, `kb:row`.
- Related:
  - `kb:Deadline` with `kb:topic` (e.g. `assisted-operation`, `warranty-after-go-live`, `transition-assistance`);
  - `kb:Activity` (RACI) with `kb:phase`;
  - `kb:Section`;
  - `{{PREFIX}}:ComplianceItem`.

## Workflow

1. **List the items:**
   ```
   KB query 'SELECT DISTINCT ?id ?item ?applicable ?phase ?sheet ?row WHERE { ?x a {{PREFIX}}:TransitionChecklistItem ; kb:excerpt ?item . OPTIONAL { ?x kb:originalId ?id } OPTIONAL { ?x {{PREFIX}}:applicable ?applicable } OPTIONAL { ?x kb:phase ?phase } OPTIONAL { ?x kb:sheet ?sheet } OPTIONAL { ?x kb:row ?row } } ORDER BY ?row'
   ```
2. **Context, gathered once:**
   - `KB query deadlines` (assisted operation / hypercare, warranty, transition assistance, contract term);
   - `KB query requirements-by-topic --param workstream="<support|operations|transition regex>" --param section="<transition|handover|knowledge transfer regex>"`;
   - RACI activities of the transition phase, via `KB query raci-by-role` filtered in a subagent if long.
3. **Per item, state:**
   - what the proposal must commit to: deliverable or evidence, phase or moment, owner (from the RACI when available), acceptance or quality criterion;
   - the related requirements and deadlines, with sources.

   Use `KB ask "<item text key terms>"` for items whose link is not obvious. For more than about 30 items, split the work across parallel subagents by phase.
4. **Coverage** (optional; subagent): compare each item with the drafts in `docs/proposal/`. Mark it covered, partial or missing, and point to the draft section.
5. **Write** `docs/transition/<YYYY-MM-DD>-checklist-coverage.md` as a table: item | applicable | phase | what the proposal must cover | owner | related requirements and deadlines (sources) | coverage. Below the table, add the open questions. Tell the user the path.
6. **Report in chat:** counts by phase and coverage, the missing items, deadline conflicts (e.g. hypercare duration differs between documents, and which source wins).

## Improvement suggestions

End with this section only when signals appeared. Examples:
- checklist items without a phase or applicability column in the mapping;
- a transition deadline appears in several documents but has no `topics` rule;
- RACI activities for transition could not be linked to checklist items (consider a wiki note mapping them);
- proposal drafts are missing a transition section.

Offer to log the suggestions in `kb/IMPROVEMENTS.md`.
