---
name: {{PROJECT}}-proposal-section
description: Draft one section of the {{PROGRAM}} proposal following the issuer's proposal template (structure, mandatory topics, page or format limits), grounded in the request documents, contract terms, requirements, deadlines and team notes in the knowledge base, with sources cited. Use when the user asks to write, outline, expand or review a proposal section or chapter (e.g. solution, methodology, team, transition, quality, security, timeline). Writes to docs/ only. For plain questions about the documents use /kb.
---

<!-- generated by kb-setup v{{ENGINE_VERSION}} from preset rfi-proposal on {{DATE}}; regeneration shows a diff first and keeps sections marked manual -->

# {{PROJECT}}-proposal-section

Drafts a section of the proposal in the structure required by `{{PROPOSAL_TEMPLATE_FILE}}`. Its sections are in the KB as `{{PREFIX}}:ProposalTemplateSection`.

## Rules

- **Facts come from the KB.** Run from the workspace root, one simple command per Bash call. Below, `KB` means `uv run ~/.claude/skills/kb-setup/scripts/kb.py`:
  - `KB ask "<question>"`;
  - `KB query <saved-query> [--param k=v]`;
  - `KB show <id | label | IRI>`;
  - `KB search "<text>" --cls <class>`.

  Never run curator commands; they belong to `/kb`.
- **Document text only in subagents.** If a template section's instructions or a referenced passage need more than the KB excerpt, delegate to a `general-purpose` subagent. Give it a self-contained prompt; it may use `KB page-text <md> <page>` and returns a compact summary with citations. Never read `raw/` files in the main context.
- **Never write to `raw/` or `wiki/`.** Output goes to `docs/proposal/`. Drafts in `docs/` may be read back for consistency; `docs/` is never indexed by the KB.
- **Cite everything** (`file, p.N`; `file, sheet X, row N` for matrices). Mark team knowledge from wiki notes as such. Repeat engine `ALERT`/`WARNING` lines. When sources conflict, use the winning value and flag the divergence in the draft as a reviewer note.
- **Do not invent bidder facts** (team size, prices, certifications, tools, references). Use `[[TO CONFIRM: ...]]` markers for anything the KB and the user have not provided.
- The draft is written in **{{PROPOSAL_LANGUAGE}}** (the proposal language) unless the user says otherwise. Chat answers follow the user's language.

## Schema cheat sheet (do not read the .ttl)

- `{{PREFIX}}:ProposalTemplateSection`, `kb:Section`, `{{PREFIX}}:ContractClause`: label, `kb:number`, `kb:page`, `kb:excerpt`, `kb:parentSection`.
- `{{PREFIX}}:ComplianceItem` and the other requirement classes:
  - `kb:originalId`, `kb:excerpt`;
  - `{{PREFIX}}:workstream`, `{{PREFIX}}:macroRequirement`, `{{PREFIX}}:eligibility`.
- `{{PREFIX}}:EvaluationCriterion` (label, `{{PREFIX}}:weight`).
- `kb:Fact` and `kb:Deadline` (`kb:topic`, `kb:value`, `kb:date`, `kb:duration`), `kb:Milestone`.
- `kb:Activity` / `kb:RACIAssignment` (`kb:role`, `kb:raciCode`), `kb:Deliverable`.
- No inference: query concrete classes.

## Workflow

1. **Locate the template section.** Use `KB search "<section name>" --cls {{PREFIX}}:ProposalTemplateSection` (or `--cls kb:Section` if the class is not assigned). Then run `KB show <section>` to get its number, page, instructions excerpt and subsections. If the instructions continue beyond the excerpt, get the full instructions through a subagent.
2. **Collect the inputs in as few calls as possible:**
   - requirements: `KB query requirements-by-topic --param workstream="<regex>" --param section="<regex>"`;
   - security: `KB query security-requirements`, when relevant;
   - conditions and dates: `KB query deadlines` (validity, hypercare, warranty, transition assistance);
   - key terms: `KB ask` for evaluation criteria, contract clauses and wiki notes with team decisions or solution descriptions.
3. **Outline first.** Show the outline: template headings, the requirements and criteria each heading must address, and what is still missing. For a long section, get the user's OK before drafting.
4. **Draft** `docs/proposal/<NN>-<section-slug>.md`:
   - a front block: template section and page, date, status draft, sources;
   - the template's heading structure;
   - per heading, prose that answers the mandatory points, with inline source references and `[[TO CONFIRM]]` markers;
   - at the end, a coverage table (requirement or criterion → where it is addressed) and the reviewer notes (conflicts, assumptions).

   Respect any page or format limit stated in the template.
5. **Consistency check** (subagent, if other drafts exist in `docs/proposal/`): numbers, durations and names must match across sections and must match the winning KB values.
6. **Report in chat:** path written, coverage counts, open `[[TO CONFIRM]]` items, conflicts.

## Improvement suggestions

End with this section only when signals appeared. Examples:
- the template section has no `{{PREFIX}}:ProposalTemplateSection` class (adjust `section_class`);
- the evaluation criteria are not in the graph (candidate for a mapping or a prose extraction);
- team knowledge was supplied in chat and should become a wiki note;
- a value conflicted between documents.

Offer to log the suggestions in `kb/IMPROVEMENTS.md`.
